# Generated by Django 3.2.6 on 2021-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publication_date', models.DateField()),
                ('ISBN_number', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('cover_page', models.ImageField(upload_to='')),
                ('language', models.CharField(max_length=150)),
            ],
        ),
    ]
